name: Markdownlint

on:
  push:
    paths:
    - "**/*.md"
    - ".markdownlint.json"
  pull_request:
    paths:
    - "**/*md"
    - ".markdownlint.json"
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js
      uses: actions/setup-node@v4.0.1
    - name: Run Markdownlint
      run: |
        npm i -g markdownlint-cli
        markdownlint "**/*.md"
    
