name: CSS Stylelint

on:
  push:
    paths:
    - "**.css"
    - ".stylelintrc.json"
  pull_request:
    paths:
    - "**.css"
    - ".stylelintrc.json"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js
      uses: actions/setup-node@v4.0.1
    - name: Run Stylelint
      run: |
        npm install stylelint-config-standard -g
        npx stylelint "src/**/*.css"
